#define MH000I "MH000I: In function msgh_init()"
#define MH000E "MH000E: Error : malloc in msgh_init()"
#define MH001I "MH001I: MsgH initialized correctly"
#define MH001E "MH001E: Error : realloc in msgh_init()"
#define MH002E "MH002E: Error : can't create a DLL in msgh_init()"
#define MH020I "MH020I: In function msg_add()"
#define MH020E "MH020E: Error : can't add a message in a MsgH without initializing it first"
#define MH024I "MH024I: message was successfully added"
#define MH023E "MH023E: Error occured when trying to add a message in the DLL)"
#define MH030I "MH030I: In function msg_display()"
#define MH031I "MH031I: message displayed correctly"
#define MH030E "MH030E: Error : this msgH is not initialized yet"
#define MH031E "MH031E: Error when reading a message in msg_display()"
